# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'currency-conversion-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Swinject'
  # Pods for currency-conversion-app

  target 'currency-conversion-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'currency-conversion-appUITests' do
    # Pods for testing
  end

end
